default:
    image: ubuntu:22.10

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - |
      which make > /dev/null || (
        apt-get update
        apt-get install -y make cmake ninja-build
        apt-get install -y g++ libncurses-dev
      )
    - make debug
  artifacts:
    paths:
      - build/

unit-test-job:
  stage: test
  script:
    - |
      which make > /dev/null || (
        apt-get update
        apt-get install -y make cmake ninja-build
        apt-get install -y g++ libncurses-dev
      )
    - make test
  dependencies:
    - build-job
  artifacts:
    paths:
      - build/

coverage-test-job:
  stage: test
  script:
    - |
      which make > /dev/null || (
        apt-get update
        apt-get install -y make cmake ninja-build
        apt-get install -y g++ libncurses-dev
        apt-get install -y lcov
      )
    - make coverage
  dependencies:
    - build-job
  artifacts:
    paths:
      - build/

package-test-job:
  stage: test
  script:
    - |
      which make > /dev/null || (
        apt-get update
        apt-get install -y make cmake ninja-build
        apt-get install -y g++ libncurses-dev
        apt-get install -y git
      )
    - make package-test

deploy-job:
  stage: deploy
  script:
    - |
      which make > /dev/null || (
        apt-get update
        apt-get install -y make cmake ninja-build
        apt-get install -y g++ libncurses-dev
      )
    - make release
