default:
    image: ubuntu:22.04

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - |
      apt-get update
      apt-get install -y make cmake ninja-build
      apt-get install -y g++ libncurses-dev
    - rm -rf build/debug
    - LIPS_TEST_TAGS='~[root]' make debug
  artifacts:
    paths:
      - build/

unit-test-job:
  stage: test
  script:
    - |
      apt-get update
      apt-get install -y make cmake ninja-build
      apt-get install -y g++ libncurses-dev
    - LIPS_TEST_TAGS='~[root]' make test
  dependencies:
    - build-job
  artifacts:
    paths:
      - build/

coverage-test-job:
  stage: test
  script:
    - |
      apt-get update
      apt-get install -y make cmake ninja-build
      apt-get install -y g++ libncurses-dev
      apt-get install -y lcov
    - LIPS_TEST_TAGS='~[root]' make coverage
  dependencies:
    - build-job
  artifacts:
    paths:
      - build/

package-test-job:
  stage: test
  script:
    - |
      apt-get update
      apt-get install -y make cmake ninja-build
      apt-get install -y g++ libncurses-dev
      apt-get install -y git
    - make package-test

deploy-job:
  stage: deploy
  script:
    - |
      apt-get update
      apt-get install -y make cmake ninja-build
      apt-get install -y g++ libncurses-dev
    - rm -rf build/release
    - make release
