name: Ubuntu 22.04

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Ubuntu 22.04

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: |
        cmake --preset default

    - name: Build
      run: cmake --build --preset default

    - name: Test
      run: ctest --output-on-failure --preset default
