name: Ubuntu 18.04

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug
  CMAKE_C_COMPILER: "gcc-9"
  CMAKE_CXX_COMPILER: "g++-9"

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build \
              -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
              -DCMAKE_C_COMPILER=${{env.CMAKE_C_COMPILER}} \
              -DCMAKE_CXX_COMPILER=${{env.CMAKE_CXX_COMPILER}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
