name: Ubuntu 20.04

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake --preset make

    - name: Build
      run: cmake --build --preset make

    - name: Test
      run: ctest --output-on-failure --preset make
